[project]
name = "mat_ceng"
version = "0.0.24"
description = "useful tools for civil engineering that are needed regularly in the daily tasks for a civil engineer"
readme = "README.md"
authors = [
    { name = "Mohamad Ali", email = "mohamadalitellawi@gmail.com" }
]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: Apache Software License"]
requires-python = ">=3.13"
dependencies = [
    "forallpeople>=2.7.1",
    "handcalcs>=1.9.0",
    "loguru>=0.7.3",
    "matplotlib>=3.10.7",
    "more-itertools>=10.8.0",
    "numpy>=2.3.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "pythonnet>=3.0.5",
    "pyyaml>=6.0.3",
    "rich>=14.2.0",
    "shapely>=2.1.2",
    "xlwings>=0.33.16",
]

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pip",
    "notebook",
    "ipympl>=0.9.8",
    "ipykernel>=6.30.1",
    "ipython>=9.6.0",
    "ipywidgets>=8.1.7",
    "jupyterlab>=4.4.9",
    "jupyterlab-mathjax3>=4.3.0",
    "nbconvert>=7.16.6",
    "pytest>=8.4.2",
]

[project.urls]
Home = "https://github.com/mohamadalitellawi/Civil_Engineering_Tools/"
